name: CI
on:
  push:
    branches: [ master ]
jobs:
  events:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch event on site repo
      run: |
        curl -v -XPOST -u "${{ secrets.ACCESS_USERNAME}}:${{secrets.ACCESS_TOKEN}}" -H "Content-Type: application/json" https://api.github.com/repos/gobwas/site/dispatches --data '{"event_type": "articles-update"}'


